name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{runner.os}}-go-${{hashFiles('**/go.sum')}}
          restore-keys: |
            ${{runner.os}}-go-
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -yq libgtk-3-dev libayatana-appindicator3-dev
      - name: Test
        run: |
          ./build.sh -v ./...

